nome = input("Digite o nome: ")
cpf = input("Digite o CPF: ")
rg = input("Digite o RG: ")
dataNascimento = input("Digite a data de nascimento: ")
sexo = input("Digite o sexo: ")
tipoSanguineo = input("Digite o tipo sanguíneo: ")
renda = float(input("Digite a renda: "))
endereco = input("Digite o endereço: ")
telefone = input("Digite o telefone: ")
cidade = input("Digite a cidade: ")               
estado = input("Digite o estado: ")

print(nome,"\n", cpf,"\n",rg, "\n",dataNascimento, "\n", sexo, "\n", tipoSanguineo)
print(renda,"\n", endereco,"\n", telefone,"\n", cidade,"\n", estado,"\n")
